version: "3.9"

networks:
  dockerapi-dev:
    driver: bridge

services:
  weather-1:
    environment:
      - LISTEN_PORT=5000
      - LISTEN_PORT_SSL=5001
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: AvitoWeather/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - dockerapi-dev

  weather-2:
    environment:
      - LISTEN_PORT=6000
      - LISTEN_PORT_SSL=6001
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    build:
      context: .
      dockerfile: AvitoWeather/Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
    networks:
      - dockerapi-dev

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather-1
      - weather-2
    ports:
      - "4001:4001"
    networks:
      - dockerapi-dev

 